{"uuid": "3fd9ae24-f043-4967-b427-bdaba37ea129", "children": ["8e2c4144-9f3c-4dc1-b213-ad628ab42dc7"], "befores": [{"name": "_Class__pytest_setup_method", "status": "passed", "start": 1591150167146, "stop": 1591150167146}], "afters": [{"name": "_Class__pytest_setup_method::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.\n\n", "trace": "  File \"/Users/liulin/Library/Python/3.7/lib/python/site-packages/allure_commons/_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Users/liulin/Library/Python/3.7/lib/python/site-packages/_pytest/fixtures.py\", line 796, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/liulin/Library/Python/3.7/lib/python/site-packages/_pytest/python.py\", line 751, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"/Users/liulin/Library/Python/3.7/lib/python/site-packages/_pytest/python.py\", line 662, in _call_with_optional_argument\n    func()\n  File \"/Users/liulin/lianxi/TestUI_Appium/test_case/test_login.py\", line 15, in teardown_method\n    obj.logout_action()\n  File \"/Users/liulin/lianxi/TestUI_Appium/businessView/loginView_func.py\", line 81, in logout_action\n    self.driver.find_element(*self.settings).click()\n  File \"/Library/Python/3.7/site-packages/appium/webdriver/webdriver.py\", line 284, in find_element\n    'value': value})['value']\n  File \"/Library/Python/3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Python/3.7/site-packages/appium/webdriver/errorhandler.py\", line 29, in check_response\n    raise wde\n  File \"/Library/Python/3.7/site-packages/appium/webdriver/errorhandler.py\", line 24, in check_response\n    super(MobileErrorHandler, self).check_response(response)\n  File \"/Library/Python/3.7/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1591150185524, "stop": 1591150189709}], "start": 1591150167146, "stop": 1591150189709}